--
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.40.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 10/10/2018 10:29:27 PM
-- Server version: 5.6.37
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE salestock_db;

--
-- Drop procedure `DELETE_product`
--
DROP PROCEDURE IF EXISTS DELETE_product;

--
-- Drop procedure `GET_Product_By_Category`
--
DROP PROCEDURE IF EXISTS GET_Product_By_Category;

--
-- Drop procedure `INSERT_product`
--
DROP PROCEDURE IF EXISTS INSERT_product;

--
-- Drop procedure `UPDATE_product`
--
DROP PROCEDURE IF EXISTS UPDATE_product;

--
-- Drop table `product`
--
DROP TABLE IF EXISTS product;

--
-- Set default database
--
USE salestock_db;

--
-- Create table `product`
--
CREATE TABLE product (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) DEFAULT NULL,
  price VARCHAR(20) DEFAULT NULL,
  category VARCHAR(50) DEFAULT NULL,
  subcategory VARCHAR(50) DEFAULT NULL,
  color VARCHAR(20) DEFAULT NULL,
  size VARCHAR(20) DEFAULT NULL,
  stock VARCHAR(100) DEFAULT NULL,
  inorder VARCHAR(100) DEFAULT NULL,
  code VARCHAR(50) DEFAULT NULL,
  image TEXT DEFAULT NULL,
  image_category VARCHAR(512) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  image_subcategory TEXT DEFAULT NULL,
  isDeleted INT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
)
ENGINE = MYISAM,
AUTO_INCREMENT = 74,
AVG_ROW_LENGTH = 195,
CHARACTER SET latin1,
CHECKSUM = 0,
COLLATE latin1_swedish_ci;

DELIMITER $$

--
-- Create procedure `UPDATE_product`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE UPDATE_product(IN pId int, IN pName VARCHAR(100)
  ,IN pCode VARCHAR(50)
  ,IN pPrice VARCHAR(20)
  ,IN pCategory VARCHAR(20)
  ,IN pSubcategory VARCHAR(20)
  ,IN pColor VARCHAR(10)
  ,IN pStock VARCHAR(20)
  ,IN pImage TEXT
  ,IN pImage_category TEXT
  ,IN pImage_subcategory TEXT)
BEGIN

UPDATE product
SET name = pName,
    code = pCode,
    price = pPrice,
    category = pCategory,
    subcategory = pSubcategory,
    color = pColor,
    stock = pStock,
    image = pImage,
    image_category = pImage_category,
    image_subcategory = pImage_subcategory
WHERE id = pId;

SELECT
  'success';
END
$$

--
-- Create procedure `INSERT_product`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE INSERT_product(IN pName VARCHAR(100)
  ,IN pCode VARCHAR(50)
  ,IN pPrice VARCHAR(20)
  ,IN pCategory VARCHAR(20)
  ,IN pSubcategory VARCHAR(20)
  ,IN pColor VARCHAR(10)
  ,IN pStock VARCHAR(20)
  ,IN pImage TEXT
  ,IN pImage_category TEXT
  ,IN pImage_subcategory TEXT)
BEGIN

INSERT INTO product (name, code, price, category, subcategory, color, stock, image, image_category, image_subcategory)
  VALUES (pName, pCode, pPrice, pCategory, pSubcategory, pColor, pStock, pImage, pImage_category, pImage_subcategory);

SELECT
  'success';
END
$$

--
-- Create procedure `GET_Product_By_Category`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE GET_Product_By_Category(IN params VARCHAR(20))
BEGIN
SELECT
  *
FROM product
WHERE isDeleted != 1;
END
$$

--
-- Create procedure `DELETE_product`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE DELETE_product(IN pId INT)
BEGIN

UPDATE product
SET isDeleted = 1
WHERE id = pId;

SELECT
  'success';
END
$$

DELIMITER ;

-- 
-- Dumping data for table product
--
INSERT INTO product VALUES
(1, 'Deacvr Abstrak V-Neck Mini Dress', '100000', 'dress', 'mini', 'merah', NULL, 'M, L, XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/b1586b44d0f5979614986a0943a15133.jpg', '', '', 1),
(2, 'Deacvr Abstrak V-Neck Mini Dress', '120000', 'dress', 'mini', 'merah', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/b1586b44d0f5979614986a0943a15133.jpg', '', '', 0),
(3, 'Cacvr Abstrak V-Neck Mini Dress', '10000', 'dress', 'mini', 'biru', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/fc4200bed81307a5b6c0f7e6cf0bf968.jpg', '', '', 0),
(4, 'Cacvr Abstrak V-Neck Mini Dress', '50000', 'dress', 'mini', 'biru', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/b1586b44d0f5979614986a0943a15133.jpg', '', '', 0),
(5, 'Vacvar Abstrak V-Neck Mini Dress', '200000', 'dress', 'midi', 'biru', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/9351dafb8500058fb5269335e8e01245.jpg', '', '', 0),
(6, 'Vacvar Abstrak V-Neck Mini Dress', '200000', 'dress', 'maxi', 'biru', NULL, 'M,L', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/5740b33c7e49e85d0d4e4cb51ae77af7.jpg', '', '', 0),
(7, 'Vacvar Abstrak V-Neck Mini Dress', '200000', 'dress', 'maxi', 'putih', NULL, 'M,L', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/b1586b44d0f5979614986a0943a15133.jpg', '', '', 0),
(8, 'Vacvar Abstrak V-Neck Mini Dress', '100000', 'dress', 'maxi', 'putih', NULL, 'L', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/9351dafb8500058fb5269335e8e01245.jpg', '', '', 0),
(9, 'Deacvr Abstr', '369.000', 'Dress ', 'mini Dress', 'red', NULL, '20', NULL, 'SSI', 'https:&#x2F;&#x2F;ss-imager-prod.freetls.fastly.net&#x2F;www-images&#x2F;480&#x2F;product_images&#x2F;fc4200bed81307a5b6c0f7e6cf0bf968.jpg', '', '', 1),
(10, 'Aber Abstr', '369.000', 'Dress ', 'mini Dress', 'red', NULL, '20', NULL, 'SSI', 'https:&#x2F;&#x2F;ss-imager-prod.freetls.fastly.net&#x2F;www-images&#x2F;480&#x2F;product_images&#x2F;345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 1),
(11, 'Aber Abstr', '369.000', 'Dress ', 'mini Dress', 'red', NULL, '20', NULL, 'SSI', 'https:&#x2F;&#x2F;ss-imager-prod.freetls.fastly.net&#x2F;www-images&#x2F;480&#x2F;product_images&#x2F;345e9d110126dc6b96e7f364a8f3672b.jpg', 'https:&#x2F;&#x2F;ss-imager-prod.freetls.fastly.net&#x2F;www-images&#x2F;480&#x2F;product_images&#x2F;345e9d110126dc6b96e7f364a8f3672b.jpg', 'https:&#x2F;&#x2F;ss-imager-prod.freetls.fastly.net&#x2F;www-images&#x2F;480&#x2F;product_images&#x2F;345e9d110126dc6b96e7f364a8f3672b.jpg', 1),
(12, 'Aber Abstr', '369.000', 'Dress ', 'mini Dress', 'red', NULL, '20', NULL, 'SSI', 'https:&#x2F;&#x2F;ss-imager-prod.freetls.fastly.net&#x2F;www-images&#x2F;480&#x2F;product_images&#x2F;345e9d110126dc6b96e7f364a8f3672b.jpg', 'https:&#x2F;&#x2F;ss-imager-prod.freetls.fastly.net&#x2F;www-images&#x2F;480&#x2F;product_images&#x2F;345e9d110126dc6b96e7f364a8f3672b.jpg', 'https:&#x2F;&#x2F;ss-imager-prod.freetls.fastly.net&#x2F;www-images&#x2F;480&#x2F;product_images&#x2F;345e9d110126dc6b96e7f364a8f3672b.jpg', 1),
(13, 'Aber Abstr', '369000', 'Dress', 'mini Dress', 'red', NULL, '20', NULL, 'SSI', 'https:&#x2F;&#x2F;ss-imager-prod.freetls.fastly.net&#x2F;www-images&#x2F;480&#x2F;product_images&#x2F;345e9d110126dc6b96e7f364a8f3672b.jpg', 'https:&#x2F;&#x2F;ss-imager-prod.freetls.fastly.net&#x2F;www-images&#x2F;480&#x2F;product_images&#x2F;345e9d110126dc6b96e7f364a8f3672b.jpg', 'https:&#x2F;&#x2F;ss-imager-prod.freetls.fastly.net&#x2F;www-images&#x2F;480&#x2F;product_images&#x2F;345e9d110126dc6b96e7f364a8f3672b.jpg', 1),
(14, 'Aber Abstr', '369000', 'Dress', 'mini Dress', 'red', NULL, '20', NULL, 'SSI', 'https:&#x2F;&#x2F;ss-imager-prod.freetls.fastly.net&#x2F;www-images&#x2F;480&#x2F;product_images&#x2F;345e9d110126dc6b96e7f364a8f3672b.jpg', 'https:&#x2F;&#x2F;ss-imager-prod.freetls.fastly.net&#x2F;www-images&#x2F;480&#x2F;product_images&#x2F;345e9d110126dc6b96e7f364a8f3672b.jpg', 'https:&#x2F;&#x2F;ss-imager-prod.freetls.fastly.net&#x2F;www-images&#x2F;480&#x2F;product_images&#x2F;345e9d110126dc6b96e7f364a8f3672b.jpg', 1),
(15, 'Aber Abstr', '369000', 'Dress ', 'mini Dress', 'red', NULL, '20', NULL, 'SSI', 'https:&#x2F;&#x2F;ss-imager-prod.freetls.fastly.net&#x2F;www-images&#x2F;480&#x2F;product_images&#x2F;345e9d110126dc6b96e7f364a8f3672b.jpg', '', 'https:&#x2F;&#x2F;ss-i', 1),
(16, 'Aber Abstr', '39000', 'Dress ', 'midi', 'hitam', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(17, 'Aber Abstr', '129000', 'Dress ', 'maxi', 'red', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(18, 'Aber Abstr', '369000', 'Dress ', 'mini Dress', 'red', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(19, 'Aber Abstr', '369000', 'Dress ', 'mini Dress', 'red', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(20, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(21, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(22, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(23, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(24, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(25, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(26, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(27, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(28, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(29, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(30, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(31, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(32, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(33, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(34, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(35, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(36, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(37, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(38, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(39, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(40, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(41, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(42, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(43, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(44, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(45, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(46, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(47, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(48, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(49, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(50, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(51, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(52, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(53, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(54, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(55, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(56, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(57, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(58, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(59, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(60, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(61, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(62, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(63, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(64, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(65, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(66, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(67, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(68, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(69, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(70, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(71, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(72, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0),
(73, 'Aber Abssstr', '269000', 'Dress ', 'mini', 'white', NULL, 'M,L,XL', NULL, 'SSI', 'https://ss-imager-prod.freetls.fastly.net/www-images/480/product_images/345e9d110126dc6b96e7f364a8f3672b.jpg', '', '', 0);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;